In [22]:
import pandas as pd
import csv

In [23]:
df_metrics = pd.read_csv('C:/Users/PC/Desktop/mitacs/Projet/ansible/playbooks/Model/metrics.csv')
df_smells = pd.read_csv('C:/Users/PC/Desktop/mitacs/Projet/ansible/playbooks/Model/sorted_manual.csv')

In [24]:
df_smells

,Playbook Path,Play Name,Task Name,duplicated code,complex playbook,high playbook coupling,Large Playbook,Unnecessary set_fact,Overriding facts,Incohesive Playbook,Unecessary Abstraction,Insufficient Modularization,Inconsistent Naming Convention,Large Play,Unnamed Play,Large Task,Long Task Name,Filename,Full_Path_and_Filename,GroupID
0,C:\Users\PC\Desktop\mitacs\Projet\ansible\play...,NaN,NaN,0,0,0,0,0,0,1,0,0,0,#,#,#,#,Amazon,C:\Users\PC\Desktop\mitacs\Projet\ansible\play...,Amazon
1,NaN,NaN,remove python-requests,#,#,#,#,#,#,#,#,#,#,#,#,0,0,Amazon,nan_Amazon,Amazon
2,NaN,NaN,install needed pip packages,#,#,#,#,#,#,#,#,#,#,#,#,0,0,Amazon,nan_Amazon,Amazon
3,NaN,NaN,letsencrypt renewal cronjob,#,#,#,#,#,#,#,#,#,#,#,#,0,0,Amazon,nan_Amazon,Amazon
4,NaN,NaN,re-install cloud-init,#,#,#,#,#,#,#,#,#,#,#,#,0,0,Amazon,nan_Amazon,Amazon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2282,C:\Users\PC\Desktop\mitacs\Projet\ansible\play...,NaN,NaN,0,0,0,0,0,0,0,0,0,0,#,#,#,#,workers,C:\Users\PC\Desktop\mitacs\Projet\ansible\play...,workers
2283,NaN,NaN,join workers to the initialized kubernetes clu...,#,#,#,#,#,#,#,#,#,#,#,#,0,0,workers,nan_workers,workers
2284,C:\Users\PC\Desktop\mitacs\Projet\ansible\play...,NaN,NaN,0,0,0,0,0,0,0,0,0,0,#,#,#,#,write-outputs,C:\Users\PC\Desktop\mitacs\Projet\ansible\play...,write-outputs
2285,NaN,NaN,Write out tripleo-undercloud-outputs.yaml,#,#,#,#,#,#,#,#,#,#,#,#,0,0,write-outputs,nan_write-outputs,write-outputs
2286,NaN,NaN,Write out tripleo-undercloud-passwords.yaml,#,#,#,#,#,#,#,#,#,#,#,#,0,0,write-outputs,nan_write-outputs,write-outputs

In [25]:
df_smells = df_smells.drop(['Playbook Path', 'Play Name', 'Task Name', 'Filename', 'Full_Path_and_Filename', 'GroupID'], axis=1)

In [26]:
df_smells

,duplicated code,complex playbook,high playbook coupling,Large Playbook,Unnecessary set_fact,Overriding facts,Incohesive Playbook,Unecessary Abstraction,Insufficient Modularization,Inconsistent Naming Convention,Large Play,Unnamed Play,Large Task,Long Task Name
0,0,0,0,0,0,0,1,0,0,0,#,#,#,#
1,#,#,#,#,#,#,#,#,#,#,#,#,0,0
2,#,#,#,#,#,#,#,#,#,#,#,#,0,0
3,#,#,#,#,#,#,#,#,#,#,#,#,0,0
4,#,#,#,#,#,#,#,#,#,#,#,#,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2282,0,0,0,0,0,0,0,0,0,0,#,#,#,#
2283,#,#,#,#,#,#,#,#,#,#,#,#,0,0
2284,0,0,0,0,0,0,0,0,0,0,#,#,#,#
2285,#,#,#,#,#,#,#,#,#,#,#,#,0,0
2286,#,#,#,#,#,#,#,#,#,#,#,#,0,0

In [27]:
df_combined = pd.concat([df_metrics, df_smells], axis=1)

In [28]:
df_combined

,Playbook Name,Play Name,Task Name,LOC_playbook,num_plays,num_tasks_playbook,avg_task_playbook,Num_Imports,Num_Roles,similarity,...,Unnecessary set_fact,Overriding facts,Incohesive Playbook,Unecessary Abstraction,Insufficient Modularization,Inconsistent Naming Convention,Large Play,Unnamed Play,Large Task,Long Task Name
0,C:\Users\PC\Desktop\mitacs\Projet\ansible\play...,NaN,NaN,22.0,0.0,4.0,6.0,0.0,0.0,0.445803,...,0,0,1,0,0,0,#,#,#,#
1,NaN,NaN,remove python-requests,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,#,#,#,#,#,#,#,#,0,0
2,NaN,NaN,install needed pip packages,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,#,#,#,#,#,#,#,#,0,0
3,NaN,NaN,letsencrypt renewal cronjob,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,#,#,#,#,#,#,#,#,0,0
4,NaN,NaN,re-install cloud-init,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,#,#,#,#,#,#,#,#,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2282,C:\Users\PC\Desktop\mitacs\Projet\ansible\play...,NaN,NaN,13.0,0.0,1.0,3.0,0.0,0.0,1.000000,...,0,0,0,0,0,0,#,#,#,#
2283,NaN,NaN,join workers to the initialized kubernetes clu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,#,#,#,#,#,#,#,#,0,0
2284,C:\Users\PC\Desktop\mitacs\Projet\ansible\play...,NaN,NaN,9.0,0.0,2.0,4.0,0.0,0.0,1.000000,...,0,0,0,0,0,0,#,#,#,#
2285,NaN,NaN,Write out tripleo-undercloud-outputs.yaml,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,#,#,#,#,#,#,#,#,0,0
2286,NaN,NaN,Write out tripleo-undercloud-passwords.yaml,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,#,#,#,#,#,#,#,#,0,0

In [29]:
# Sauvegarder le DataFrame dans un fichier CSV
df_combined.to_csv('C:/Users/PC/Desktop/mitacs/Projet/ansible/playbooks/Model/df_combined.csv', index=False)